spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/** 

        - id: order-lines-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**

        - id: products-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
server:
  port: 8222