spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: riyas
    password: riyas
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: riyas
    password: riyas

server:
  port: 8050

