spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: riyas
    password: riyas
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: riyas
    password: riyas
  
minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: admin123
  bucket: product-images

server:
  port: 8050

