spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      port: 27017
      database: customer
      username: riyas
      password: riyas
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.riyas.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.riyas.ecommerce.Notification.PaymentNotificationRequest 


  mail:
    host: localhost
    port: 1025
    username: riyas
    password: riyas
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          trust: '*'
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040