services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: riyas
      POSTGRES_PASSWORD: riyas
      PGDATA: /var/lib/postgressql/data
    volumes:
      - postgres:/var/lib/postgressql/data
    ports:
      - 5432:5432
    networks:
      - microservice-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE : 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservice-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=riyas
      - MONGO_INITDB_ROOT_PASSWORD=riyas
#    networks:
#      - microservice-net
#    restart: unless-stopped

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      -  8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=riyas
      - ME_CONFIG_MONGODB_ADMINPASSWORD=riyas
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025






networks:
  microservice-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:

