CREATE TABLE IF NOT EXISTS category (
  id INTEGER NOT NULL PRIMARY KEY,
  description VARCHAR(255),
  name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  available_quantity DOUBLE PRECISION NOT NULL,
  price NUMERIC (38,2),
  category_id INTEGER CONSTRAINT fk_category
    REFERENCES category(id)
);

CREATE SEQUENCE IF NOT EXISTS category_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS products_seq INCREMENT BY 50;

